### ISSUE TITLE
sqasm hangs in case of incorrectly positioned label

### ISSUE THREAD

**Issue by Vort** [mazonka/code#1]
When I assemble such file, result is generated without problems:
```
H (-1)
0 0 (-1)
.H: 'H'
```
But if I reorder instructions slightly, sqasm hangs and tries to consume all my RAM:
```
H (-1)
0 0 (-1)
H:
.'H'
```

If second variant is wrong and should not be supported, then it is better to write error message instead of hanging.

**Comment by mazonka** [comment]
fixed

**Comment by Vort** [comment]
Thank you.
